server {
    listen 80;
    listen [::]:80;
    server_name void.scooom.xyz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name void.scooom.xyz;
    root /var/www/void.scooom.com/public;

    client_max_body_size 100M;

    ssl_certificate /etc/letsencrypt/live/void.scooom.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/void.scooom.xyz/privkey.pem;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.4-void.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    error_log /var/log/nginx/void_error.log;
    access_log /var/log/nginx/void_access.log;
}
